### ISSUE TITLE
Is there a possibility to turn off the tg= link conversion?

### ISSUE THREAD

**Issue by kenodressel** [fengkx/NodeRSSBot#218]
I would rather have the real links so telegram also fetches a preview.

**Comment by fengkx** [comment]
What do you mean by `turn off the tg= link conversion` ?

I disable preview in https://github.com/fengkx/NodeRSSBot/blob/master/source/utils/send.ts#L58.
Because It is often that one message contain more than one link. And I think it is annoying to have a preview which take off a large area of my screen sometime.

**Comment by kenodressel** [comment]
Ah okay because when I click a link on the desktop client it does not open it in a browser but instead uses a weird telegram build in browser (probably chrome). And If i select to copy a link it is `tg://unsafe_url?url=https%3A%2F%2Fxkcd.com%2F2323%2F`which makes it hard to open in an external browser

**Comment by fengkx** [comment]
The official telegram desktop has nothing like `tg://`. It should be the problem with your third party client.
